# -*- coding: utf-8 -*-
"""ainn-code-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ruckmk5KG4s6JkLqa-j6F8fctQjnrSM
"""

# Import libraries
import os
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, r2_score


# Set up paths
BASE_DIR = Path("/content")
OUTPUT_DIR = BASE_DIR / "output"
FIGURES_DIR = OUTPUT_DIR / "figs"
METRICS_PATH = OUTPUT_DIR / "metrics.csv"
DATASET_PATH = BASE_DIR / "PoC Data_105602.xlsx"  # Your file name

# Create directories
os.makedirs(FIGURES_DIR, exist_ok=True)

# Set random seed
RNG = np.random.default_rng(42)

print(f"Working directory: {BASE_DIR}")
print(f"Figures will be saved to: {FIGURES_DIR}")
print(f"Metrics will be saved to: {METRICS_PATH}")

# ============================================
# 1. LOAD YOUR DATA
# ============================================
# Simply read your Excel file directly
df = pd.read_excel(DATASET_PATH, sheet_name="synthetic_mes_smart_meter_data")
df["timestamp"] = pd.to_datetime(df["timestamp"])
df = df.set_index("timestamp")

print(f"Loaded data: {len(df):,} rows")
print(f"Date range: {df.index.min()} → {df.index.max()}")
display(df.head())
display(df.describe().T)
print(f"Missing values:\n{df.isna().sum()}")

# ============================================
# 2. FEATURE ENGINEERING
# ============================================
# Add time features if not already present
df["hour"] = df.index.hour + df.index.minute / 60
df["dow"] = df.index.dayofweek
df["doy"] = df.index.dayofyear
df["is_weekend"] = (df["dow"] >= 5).astype(int)

# Create lag features
df["lag_48"] = df["load_kwh"].shift(48)     # same time yesterday
df["lag_336"] = df["load_kwh"].shift(336)   # same time last week
df["roll_mean_48"] = df["load_kwh"].rolling(48).mean()
df = df.dropna()

features = ["hour", "dow", "is_weekend", "temperature_c", "lag_48", "lag_336", "roll_mean_48"]
target = "load_kwh"

split = int(len(df) * 0.85)
train, test = df.iloc[:split], df.iloc[split:]

X_train, y_train = train[features], train[target]
X_test, y_test = test[features], test[target]

print(f"Feature matrix shape: {df.shape}")
print(f"Train rows: {len(train):,} | Test rows: {len(test):,}")
print(f"Features: {features}")

# ============================================
# 3. MODEL TRAINING
# ============================================
model = GradientBoostingRegressor(
    n_estimators=250, max_depth=3, learning_rate=0.05, random_state=42
)
model.fit(X_train, y_train)
pred = model.predict(X_test)

mae = mean_absolute_error(y_test, pred)
mape = mean_absolute_percentage_error(y_test, pred) * 100
r2 = r2_score(y_test, pred)

print(f"MAE: {mae:.4f} kWh")
print(f"MAPE: {mape:.2f}%")
print(f"R2: {r2:.4f}")

metrics = pd.DataFrame(
    {"Metric": ["MAE (kWh)", "MAPE (%)", "R-squared"], "Value": [round(mae, 3), round(mape, 2), round(r2, 3)]}
)
metrics.to_csv(METRICS_PATH, index=False)
display(metrics)

# ============================================
# 4. VISUAL EVIDENCE
# ============================================
# Figure 4: Forecast vs Actual (last 5 days)
fig, ax = plt.subplots(figsize=(9, 4))
last = test.iloc[-240:]
last_pred = pred[-240:]
ax.plot(last.index, last[target], label="Actual demand", color="#3B1A16", linewidth=1.5)
ax.plot(last.index, last_pred, label="Forecast (GBR model)", color="#C45C4A", linewidth=1.5, linestyle="--")
ax.set_title("Figure 4. Actual versus forecast feeder demand (last 5 days of test set)")
ax.set_xlabel("Timestamp")
ax.set_ylabel("Load (kWh per half-hour)")
ax.legend()
ax.grid(alpha=0.3)
fig.autofmt_xdate()
fig.tight_layout()
fig.savefig(FIGURES_DIR / "fig4_forecast_vs_actual.png")
plt.show()

# Figure 5: Feature importance
importances = pd.Series(model.feature_importances_, index=features).sort_values()
fig, ax = plt.subplots(figsize=(7, 4))
importances.plot(kind="barh", ax=ax, color="#C45C4A")
ax.set_title("Figure 5. Relative feature importance — demand forecasting model")
ax.set_xlabel("Importance score")
fig.tight_layout()
fig.savefig(FIGURES_DIR / "fig5_feature_importance.png")
plt.show()
display(importances.to_frame("Importance"))

# Figure 6: Daily profile
profile = df.groupby(["is_weekend", "hour"])["load_kwh"].mean().unstack(level=0)
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(profile.index, profile[0], label="Weekday", color="#3B1A16")
ax.plot(profile.index, profile[1], label="Weekend", color="#C45C4A")
ax.set_title("Figure 6. Average half-hourly load profile: weekday vs weekend")
ax.set_xlabel("Hour of day")
ax.set_ylabel("Average load (kWh)")
ax.legend()
ax.grid(alpha=0.3)
fig.tight_layout()
fig.savefig(FIGURES_DIR / "fig6_daily_profile.png")
plt.show()

print("\n" + "="*50)
print("CHARTS AND METRICS GENERATED SUCCESSFULLY")
print("="*50)
print(f"Saved metrics: {METRICS_PATH}")
print("Saved figures:")
for name in ["fig4_forecast_vs_actual.png", "fig5_feature_importance.png", "fig6_daily_profile.png"]:
    print(f"  - {FIGURES_DIR / name}")

# ============================================
# AUTO-DOWNLOAD RESULTS
# ============================================
print("\n" + "="*50)
print("DOWNLOADING RESULTS TO YOUR COMPUTER...")
print("="*50)

# Download metrics
files.download(str(METRICS_PATH))

# Download figures
for fig_name in ["fig4_forecast_vs_actual.png", "fig5_feature_importance.png", "fig6_daily_profile.png"]:
    fig_path = FIGURES_DIR / fig_name
    if fig_path.exists():
        files.download(str(fig_path))

print("\n✅ All files downloaded successfully!")